Modify event on firebase
mfocshaner/Buddies pull request #17
Opened 2018-12-17 20:39 UTC by idosavion

Add the necessary function to Database Streamer and  started modifying view single event activity

2018-12-17 21:24 UTC, mharsat requested changes
All good just read the comment

2018-12-17 21:24 UTC, mharsat commented on app/src/main/java/com/huji/foodtricks/buddies/SignInActivity.java
> +        Intent signedInIntent = new Intent(this, EventsTabsActivity.class);
We already removed this because sign in works from all devices

2018-12-18 08:26 UTC, mfocshaner reviewed
Looks really cool!
visual changes needed for next iteration (next PR, or this one if you have time):
- "Going?" is clickable, should be disabled
- background of buttons is white and not gray like the background; we need to ask the design team if it's ok.
- Once a button has been clicked, I think it should change its color.

Good job! <3

2018-12-18 08:26 UTC, mfocshaner commented on app/src/main/java/com/huji/foodtricks/buddies/DatabaseStreamer.java
> +    public void modifyEvent(EventModel eventModel, String eventModelId,
can you rename `(EventModel eventModel)` to `modifiedEventModel` or `updatedEventModel`, just os it's clear that it's the new one and not the old one?

2018-12-18 08:26 UTC, mfocshaner commented on app/src/main/java/com/huji/foodtricks/buddies/ViewSingleEventActivity.java
> +                    uId = FirebaseAuth.getInstance().getCurrentUser().getUid(); // Should use getIntent().getSerializable
Just to make sure, uId is the UserModel's key in the database, not the Authentication key.

2018-12-19 08:24 UTC, idosavion commented on app/src/main/java/com/huji/foodtricks/buddies/SignInActivity.java
> +        Intent signedInIntent = new Intent(this, EventsTabsActivity.class);
fixed

2018-12-19 08:24 UTC, idosavion commented on app/src/main/java/com/huji/foodtricks/buddies/DatabaseStreamer.java
> +    public void modifyEvent(EventModel eventModel, String eventModelId,
renamed

2018-12-19 08:25 UTC, idosavion commented on app/src/main/java/com/huji/foodtricks/buddies/ViewSingleEventActivity.java
> +                    uId = FirebaseAuth.getInstance().getCurrentUser().getUid(); // Should use getIntent().getSerializable
yes

2018-12-19 08:28 UTC, idosavion commented
All fixed,
about the buttons in ViewSingleEventActivity: the activity is not finished but to avoid conflicts I want to merge the significant changes as fast as possible

2018-12-19 14:41 UTC, mfocshaner commented on app/src/main/java/com/huji/foodtricks/buddies/ViewSingleEventActivity.java
>  //        setContentView(R.layout.activity_view_single_event);
remove comment, add:
`selectedButtonView.setEnabled(false);`

2018-12-19 14:52 UTC, mharsat approved these changes

2018-12-19 15:03 UTC, merged